[package]
name = "adaptiveRouting"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.23"
tokio = { version = "1", features = ["full"] }
futures = "0.3.30"
serde_json = "1.0.143"
futures-util = "0.3.31"
